{% set data= load_setup_py_data() %}
package:
  name: ts-mtdome
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_mtdome = lsst.ts.mtdome.cli:execute_csc
  script_env:
    - PATH
    - LD_LIBRARY_PATH
    - OSPL_HOME
    - PYTHON_BUILD_LOCATION
    - LSST_DDS_PARTITION_PREFIX
    - TS_CONFIG_MTTCS_DIR

test:
  requires:
    - ts-conda-build =0.3
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
  source_files:
    - python
    - bin
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - py.test

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
